### ISSUE TITLE
Can't connect to Splunk free version

### ISSUE THREAD

**Issue by fenice2** [swedishmike/dmarcparser#1]
Hi

I've just been trying to forward my dmarc reports to splunk but I have the 'free' version of splunk and obviously I don't have any credentials to connect to my splunk instance. Is there currently workaround for this?

Regards

bill

**Comment by swedishmike** [comment]
Bill, 

As far as I know it should work the same even if you use a 'free/development license'. 

Have you enabled the correct data source etc? http://docs.splunk.com/Documentation/Splunk/7.1.0/Data/WhatSplunkcanmonitor

Cheers, Mike

**Comment by swedishmike** [comment]
Since I might be mis-understanding you here:  Exactly what do you mean by the 'free' version of Splunk?

**Comment by fenice2** [comment]
Thanks for your quick reply.

The 'free' (also called the 'light') version does not require any login credentials and it has a maximum of 500MB of data per-day for indexing. Obvious your code is for the Splunk Enterprise version that does have login credentials. Basically I just need to be able to send data to a specific port on the splunk server.

Regards

Bill

**Comment by swedishmike** [comment]
Bill,

No worries at all - more fun than dealing with my actual job... ;)

Ahh... I'm afraid that I've never tried that one. I've always used Splunk Enterprise with a development license for my testing/dev usage and then pointed live environments to our full licensed install.

I did a quick search and it seems that you can't point the API etc towards these other versions: https://answers.splunk.com/answers/444286/is-rest-api-access-available-in-splunk-light.html :(

I can think of two possible solutions here....

1. Get yourself a Splunk Enterprise install with a development license.

2. Hack my script a bit and instead of sending the data over the SDK/http you could write it to a textfile and then use a normal Splunk forwarder to send that to your Splunk instance?

Cheers, Mike

**Comment by fenice2** [comment]
Hi Mike

I'm only a home user and run a private mail server so the development license for me seems a bit excessive. The write to a text file and forward it sounds good to me and the easiest. :)

Regards


Bill

**Comment by swedishmike** [comment]
Bill,

Yeah - in those circumstances I think the second option makes the most sense.

Let me know if you're ok to close this issue as it is for now?

Cheers, Mike

**Comment by fenice2** [comment]
Yes, I'll close this issue. Thanks again for your help and have a good week-end.

Regards


Bill

**Comment by swedishmike** [comment]
Bill,

Absolutely no worries at all - glad that I could be of at least some help.

Thank you and the same to you!

// Mike
